apiVersion: v1
kind: Secret
metadata:
    name: ping-pong-postgres-secret
    namespace: exercises
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:YlQ2V7zRmuM=,iv:AUC652b2MB2B/yh+4GtlEnptA2W2XaO81l12jQQ46m0=,tag:A4BT0rkAhm96zwc4VTEfeg==,type:str]
sops:
    age:
        - recipient: age12hlqsxnr76q884zjhzh3up3x9jpf939k29fu3vdmy5fxyhklcfmqs00g4x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBodzgzUEYxUWQ3dm9yeEE5
            VFFuc2l2TTcxNUw1eUdSNjZGUU80b1EvSVRVCkJoaFRaU1Fic0daeVF2UnZsQlRK
            QVgvVkZMVEZFOHlCVTRjeEJPbDc2SWcKLS0tIDg4T2hGclBRckZ5b2FNYXQrYzE0
            U3E4d3FmQlRBdDZ5eWtmNE55Zm02M2cKMZZ01sKCLlsYOFf9JBDXVHhe0jGm4GpR
            7ET6dlV+fLw7lbiEPxiLPNf/mbJZT8P1it78CimHIH9pGArVGJ3k2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T05:16:46Z"
    mac: ENC[AES256_GCM,data:5E3HgZm+X+F16SbQy0Evm3KeN6WRFtVxNoZnGWbbSnPV28GLG8x6ChTndBHeunCx0HXUUR+knSbiBGYDgqDDXJrBtbpayUnbgV5f6UsVCIbWQR9Ox7jPBTKjyv8W+ZpSWf1KYJ5UFJ3mJoemAQYeh/uzRjOcaM3J2oFzpv8Y6lQ=,iv:vQocegaRjDNhQdXhLdNLwlhKmp4G3Ww41+pECMlxK60=,tag:vGmTUnVFuG7Ly2ho/YkPQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
