apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: ping-pong-svc
spec:
  type: LoadBalancer # Cloud default
  # type: ClusterIP <-- Change to ClusterIP if LoadBalancer is not supported, ie. on local clusters
  selector:
    app: ping-pong
  ports:
    - port: 2347
      protocol: TCP
      targetPort: 8085
