apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: ping-pong-svc
spec:
  type: ClusterIP # <- Used with GKE Gateway API
  selector:
    app: ping-pong
  ports:
    - port: 80 # <- Used with GKE Gateway API (http)
      protocol: TCP
      targetPort: 8085
