# Used for to-do-v3 CI/CD pipeline in staging environment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ./../../base
- to-do-postgres-backup-cronjob.yaml

images:
- name: to-do-backend
  newName: villejuhan1/todo-backend
  newTag: 7e8baa573cc057aee241e2b93d378cf9f6bb4a1c
- name: to-do-frontend
  newName: villejuhan1/todo-frontend
  newTag: 7e8baa573cc057aee241e2b93d378cf9f6bb4a1c
