# Used for to-do-v3 CI/CD pipeline in staging environment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ./../../base
- to-do-postgres-backup-cronjob.yaml
- to-do-postgres-backup-service-account.yaml

images:
- name: to-do-backend
  newName: villejuhan1/todo-backend
  newTag: e55843f1c11168931b24ecb780b1172bdc224eb4
- name: to-do-frontend
  newName: villejuhan1/todo-frontend
  newTag: e55843f1c11168931b24ecb780b1172bdc224eb4
