# Used for to-do-v3 CI/CD pipeline in staging environment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
- ./../../base
- to-do-postgres-backup-cronjob.yaml

images:
- name: to-do-backend
  newName: villejuhan1/todo-backend
  newTag: 1399f065f3eef5785b3011e0c8900aaf5673efea
- name: to-do-frontend
  newName: villejuhan1/todo-frontend
  newTag: 1399f065f3eef5785b3011e0c8900aaf5673efea
