apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverino-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serverino
  template:
    metadata:
      labels:
        app: serverino
    spec:
      containers:
        - name: serverino
          image: villejuhan1/serverino:1_2
          env:
            - name: PORT
              value: "3002"
          ports:
            - containerPort: 3002
