# Used for to-do-v2 CI/CD pipeline, doesn't include everything, just the necessary parts
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project

resources:
- to-do-backend-deployment.yaml
- to-do-frontend-deployment.yaml
- to-do-frontend-svc.yaml

images:
- name: to-do-backend
  newName: villejuhan1/todo-backend
  newTag: f542d84b5e2183da88bf6dc426a0447d05ae5eac
- name: to-do-frontend
  newName: villejuhan1/todo-frontend
  newTag: f542d84b5e2183da88bf6dc426a0447d05ae5eac
