# Namespace for to-do project
kind: Namespace
apiVersion: v1
metadata:
  name: project
  labels:
    name: project
---
# ReferenceGrant to allow HTTPRoute in 'project' namespace to reference Service in 'default' namespace
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-default-gateway
  namespace: project
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: default
  to:
    - group: ""
      kind: Service
---

