# Autoscaler for to-do backend and frontend deployments
# It references the limitranges defined in to-do-limitrange.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: to-do-backend-hpa
  namespace: project
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: to-do-backend
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: to-do-frontend-hpa
  namespace: project
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: to-do-frontend
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
