apiVersion: v1
kind: Secret
metadata:
    name: to-do-postgres-secret
    namespace: project
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:aqBLwFyl9tv+oPFw5g==,iv:K1mx8l+HrTmdZvgm42iwk/yIMJ0tBwawsWsPeXkD3i8=,tag:o+LLOZpBI2KmcfO0BjPAhQ==,type:str]
sops:
    age:
        - recipient: age12hlqsxnr76q884zjhzh3up3x9jpf939k29fu3vdmy5fxyhklcfmqs00g4x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZWl6UFUwZHh4emFiS3BY
            aXpsRXdtRjVGcnh6ZFFjRG9NcnZJSi96VWpnCkFhYkFhYUhNaXdTcHg5VzRYczFm
            UWIyZDM0MHRZbXZrK0p2Skxjd294d00KLS0tIE90RFVSd1dzY3laZlo2YW04MDR0
            dlFuK21ISlVnemVUS2hNOHVVL2U1bXMKidq/0MU8vmEaXF2jxP1Pw2a7rNiT2Ce3
            +lFSAuppXgAf4RODporf0bghZZu86su1sRimi0tRfHTV+AfUmLUW7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T09:13:50Z"
    mac: ENC[AES256_GCM,data:37UB1lIoC4Ci63iiZ2/gHhXRiXPAsAFCaXLB7eEnTfxJUGllRfn8tW/dJ8RgauechSpM+pD4S/c4/ULnGsFa4SIvXi3Ii7l0ysMekTE0OsQUB9FAxq3VT/QHLGQ27bx0AXgSqpbAQiUBFyYxvVbLeHb60VRUpn3URb9rv66obHg=,iv:QvWTPXBKTH5T9z5DBb/DrbwqK2RV60D4t5ev+CasdeE=,tag:sMpi5efGCunk5+slyh2W1g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
