apiVersion: v1
kind: ServiceAccount
metadata:
  name: pg-backup-sa
  namespace: project
  annotations:
    iam.gke.io/gcp-service-account: pg-backup@vjn-devops-with-kubernetes.iam.gserviceaccount.com
