# Used for to-do-v3 CI/CD pipeline in staging environment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./to-do-backend-deployment.yaml
  - ./to-do-frontend-deployment.yaml
  - ./to-do-frontend-loadbalancer.yaml
  - ./to-do-postgres-statefulset.yaml
  - ./to-do-backend-volume.yaml
