kind: Namespace
apiVersion: v1
metadata:
  name: exercises
  labels:
    name: exercises
---
# ReferenceGrant to allow HTTPRoute in 'default' namespace to reference Service in 'exercises' namespace
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-default-gateway
  namespace: exercises
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: default
  to:
    - group: ""
      kind: Service
---

