apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: exercises
  name: log-output-and-pingpong-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: log-output-svc
                port:
                  number: 2346
          - path: /logs
            pathType: Prefix
            backend:
              service:
                name: log-output-svc
                port:
                  number: 2346
#          - path: /pingpong
#            pathType: Prefix
#            backend:
#              service:
#                name: ping-pong-svc
#                port:
#                  number: 2347
#          - path: /pings
#            pathType: Prefix
#            backend:
#              service:
#                name: ping-pong-svc
#                port:
#                  number: 2347
