apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-deployment
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes: # Define volume
        - name: log-data
          emptyDir: {}
        - name: log-output-configmap
          configMap:
            name: log-output-configmap
        #- name: ping-pong-log-output-pv
        #  persistentVolumeClaim:
        #    claimName: ping-pong-log-output-volume
      containers:
        - name: logger
          image: villejuhan1/log-output:logger-gc
          imagePullPolicy: Always
          volumeMounts: # Mount volume
            - name: log-data
              mountPath: /log
        - name: log-response
          image: villejuhan1/log-output:web-gc
          imagePullPolicy: Always
          env:
            - name: PINGS_API
              value: "http://ping-pong-svc:80"
            - name: LOG_PATH
              value: "/log"
            - name: CONFIG_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-configmap
                  key: MESSAGE
          volumeMounts: # Mount volume
            - name: log-data
              mountPath: /log
            - name: log-output-configmap
              mountPath: /tmp
            #- name: ping-pong-log-output-pv
            #  mountPath: /shared
