apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes: # Define volume
        - name: log-data
          emptyDir: {}
        #- name: ping-pong-log-output-pv
        #  persistentVolumeClaim:
        #    claimName: ping-pong-log-output-volume
      containers:
        - name: logger
          image: villejuhan1/log-output:logger
          imagePullPolicy: Always
          volumeMounts: # Mount volume
            - name: log-data
              mountPath: /log
        - name: log-response
          image: villejuhan1/log-output:reader
          imagePullPolicy: Always
          env:
            - name: PINGS_API
              value: "http://ping-pong-svc:2347"
            - name: LOG_PATH
              value: "/log"
          volumeMounts: # Mount volume
            - name: log-data
              mountPath: /log
            #- name: ping-pong-log-output-pv
            #  mountPath: /shared
