# Persistent Volume definition for ping-pong and log-output applications
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ping-pong-log-output-pv
  namespace: exercises
spec:
  storageClassName: ping-pong-log-output-pv # this is the name you are using later to claim this volume
  capacity:
    storage: 1Gi # Could be e.q. 500Gi. Small amount is to preserve space when testing locally
  volumeMode: Filesystem # This declares that it will be mounted into pods as a directory
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/kubedata/ping-pong-log-output-pv # Path on the node where data is stored
