apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/gitops-logger-deployment.yaml
    # Tag will be set in GitHub Actions workflow
    # This is a static image for now
images:
- name: LOGGER/LOGGER
  newName: villejuhan1/log-output
  newTag: logger-gc
- name: LOGGER/WEB
  newName: villejuhan1/log-output
  newTag: web-5314490e093f004abe015543fdfab253841074dc
