apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gc-kubehelvetti-httproute
spec:
  parentRefs:
    - name: gc-kubehelvetti-gw
  rules:
    # ping-pong at /pingpong
    - matches:
        - path:
            type: PathPrefix
            value: /pingpong
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: ping-pong-svc
          port: 80

    # log-output at /
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: log-output-svc
          port: 80
