apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  PORT: "3005"
  IMAGE_PATH: "assets/random.jpg"
  DATABASE_HOST: to-do-postgres-svc.database.svc.cluster.local
  DATABASE_PORT: "5432"
  DATABASE_NAME: tododb
  DATABASE_USER: appuser
  DATABASE_PASSWORD: development
  DEV_MODE: "true" # Used for development-specific configurations
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: to-do-backend
  template:
    metadata:
      labels:
        app: to-do-backend
    spec:
      containers:
        - name: to-do-backend
          image: to-do-backend # <- Defined in the Kustomize file
          imagePullPolicy: Always
          ports:
            - containerPort: 3005
          envFrom:
            - configMapRef:
                name: backend-config
          env:
            - name: DATABASE_PASSWORD
              value: development
          volumeMounts:
            - name: assets-storage
              mountPath: /app/assets
      volumes:
        - name: assets-storage
          persistentVolumeClaim:
            claimName: backend-assets-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: to-do-backend-svc
spec:
  selector:
    app: to-do-backend
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
  type: ClusterIP
