# Used for to-do-v2 CI/CD pipeline, doesn't include everything, just the necessary parts
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - dev-httproute.yaml
  - dev-referencegrant.yaml
  - dev-to-do-volume.yaml
  - dev-to-do-backend-deployment.yaml
  - dev-to-do-frontend-deployment.yaml
  - dev-to-do-frontend-svc.yaml

images:
  - name: dev-to-do-backend
  - name: dev-to-do-frontend
