# Used for to-do-v3 CI/CD pipeline in staging environment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ./../../base

images:
- name: to-do-backend
  newName: villejuhan1/todo-backend
  newTag: b03b7a41bdb2531090ad1583ddf14db45b2fd222
- name: to-do-frontend
  newName: villejuhan1/todo-frontend
  newTag: b03b7a41bdb2531090ad1583ddf14db45b2fd222
