# Used for to-do-v3 CI/CD pipeline in staging environment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ./../../base

images:
- name: to-do-backend
  newName: villejuhan1/todo-backend
  newTag: c5e0de5f9368afab6c1e813549d74810fa340ef1
- name: to-do-frontend
  newName: villejuhan1/todo-frontend
  newTag: c5e0de5f9368afab6c1e813549d74810fa340ef1
