# Used for to-do-v3 CI/CD pipeline in staging environment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ./../../base

images:
- name: to-do-backend
  newName: villejuhan1/todo-backend
  newTag: b89a3cc867a99f959201e12d275ca97b012c94be
- name: to-do-frontend
  newName: villejuhan1/todo-frontend
  newTag: b89a3cc867a99f959201e12d275ca97b012c94be
