# Used for to-do-v3 CI/CD pipeline in staging environment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ./../../base

images:
- name: to-do-backend
  newName: villejuhan1/todo-backend
  newTag: 2c911c88240eb6a4f4ff821a34e461b9eb82f73a
- name: to-do-frontend
  newName: villejuhan1/todo-frontend
  newTag: 2c911c88240eb6a4f4ff821a34e461b9eb82f73a
