name: Deploy To-do-v2 app to GKE on a development or similar branch

on:
  push:
    branches-ignore:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: gc-kubehelvetti-2
  GKE_ZONE: europe-north1-b
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: devops-with-kubernetes
  BRANCH: ${{ github.ref_name }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker europe-north1-docker.pkg.dev --quiet

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          project_id: ${{ env.PROJECT_ID }}
          location: ${{ env.GKE_ZONE }}

      - name: Build images
        run: |
          docker build -t $REGISTRY/$PROJECT_ID/$REPOSITORY/dev-todo-backend:${{ github.sha }} part1/to-do-v2/backend
          docker build -t $REGISTRY/$PROJECT_ID/$REPOSITORY/dev-todo-frontend:${{ github.sha }} part1/to-do-v2/frontend

      - name: Push images
        run: |
          docker push $REGISTRY/$PROJECT_ID/$REPOSITORY/dev-todo-backend:${{ github.sha }}
          docker push $REGISTRY/$PROJECT_ID/$REPOSITORY/dev-todo-frontend:${{ github.sha }}

      - name: Deploy to GKE
        run: |
          kubectl create namespace ${GITHUB_REF#refs/heads/} || true
          kubectl config set-context --current --namespace=${GITHUB_REF#refs/heads/}

          cd part1/to-do-v2/branch_deployment

          ENV_NAME=${GITHUB_REF#refs/heads/}
          export ENV_NAME

          kustomize edit set image to-do-backend=$REGISTRY/$PROJECT_ID/$REPOSITORY/dev-todo-backend:${{ github.sha }}
          kustomize edit set image to-do-frontend=$REGISTRY/$PROJECT_ID/$REPOSITORY/dev-todo-frontend:${{ github.sha }}

          kustomize build . | kubectl apply -f -

          kubectl rollout status deployment dev-to-do-backend
          kubectl rollout status deployment dev-to-do-frontend
