name: Delete branch environment

on:
  delete:
  workflow_dispatch: # Allows manual triggering

jobs:
  cleanup:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GKE_PROJECT }}
      GKE_CLUSTER: gc-kubehelvetti-2
      GKE_ZONE: europe-north1-b
      BRANCH_NAME: ${{ github.ref_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      # Authenticate with GCP
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: Delete environment namespace
        run: |
          BRANCH_NAME="${{ github.event.ref }}"
          echo "Branch deleted: $BRANCH_NAME"

          # Prevent deletion of main/master namespaces
          if [[ "$BRANCH_NAME" == "main" || "$BRANCH_NAME" == "master" ]]; then
            echo "Skipping deletion of protected branch namespace: $BRANCH_NAME"
            exit 0
          fi

          echo "Deleting namespace: $BRANCH_NAME"
          kubectl delete namespace "$BRANCH_NAME" || echo "Namespace does not exist, skipping."
