name: Deploy To-do-v2 app to GKE

on:
  push:
    branches:
      - mainer # Don't want to trigger this all the time, change to "main" if necessary.

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: gc-kubehelvetti-2
  GKE_ZONE: europe-north1-b
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: devops-with-kubernetes
  NAMESPACE: project

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker europe-north1-docker.pkg.dev --quiet

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          project_id: ${{ env.PROJECT_ID }}
          location: ${{ env.GKE_ZONE }}

      - name: Build images
        run: |
          docker build -t $REGISTRY/$PROJECT_ID/$REPOSITORY/todo-backend:${{ github.sha }} part1/to-do-v2/backend
          docker build -t $REGISTRY/$PROJECT_ID/$REPOSITORY/todo-frontend:${{ github.sha }} part1/to-do-v2/frontend

      - name: Push images
        run: |
          docker push $REGISTRY/$PROJECT_ID/$REPOSITORY/todo-backend:${{ github.sha }}
          docker push $REGISTRY/$PROJECT_ID/$REPOSITORY/todo-frontend:${{ github.sha }}

      - name: Deploy to GKE
        run: |
          kubectl create namespace $NAMESPACE || true
          kubectl config set-context --current --namespace=$NAMESPACE

          cd part1/to-do-v2/manifests

          kustomize edit set image to-do-backend=$REGISTRY/$PROJECT_ID/$REPOSITORY/todo-backend:${{ github.sha }}
          kustomize edit set image to-do-frontend=$REGISTRY/$PROJECT_ID/$REPOSITORY/todo-frontend:${{ github.sha }}

          kubectl delete deployment to-do-backend -n $NAMESPACE || true

          kustomize build . | kubectl apply -f -

          kubectl rollout status deployment to-do-backend
          kubectl rollout status deployment to-do-frontend
